[Utils] Add Stitcher class for overlapping chunked encoded samples
clara-parabricks/VariantWorks pull request #106
Opened 2020-08-24 15:16 UTC by ohadmo

2020-09-03 22:31 UTC, tijyojwad requested changes

2020-09-03 22:31 UTC, tijyojwad commented on variantworks/utils/stitcher.py
> +    def __init__(self, probs, positions, label_symbols=None):
for label_symbols, what do you think of making that a required argument that's a callable. so we can just call that argument with the data at index `i` (like on line 45) and get the decoded base back

2020-09-03 22:31 UTC, tijyojwad commented on variantworks/utils/stitcher.py
> +class Stitcher:
I'm wondering if we could just making this a function as opposed to a class. The stitch function can just take in the probs, positions, chunk_len and decoder.

2020-09-08 16:59 UTC, o8191 commented on variantworks/utils/stitcher.py
> +    def __init__(self, probs, positions, label_symbols=None):
@tijyojwad I'm adding \__getitem__ method check for now,  But eventually, we want to use the exact same labels used in https://github.com/clara-parabricks/VariantWorks/blob/b81f3da334fb3d161a9230ff99d22714606c37da/variantworks/encoders.py#L170

I want to maybe an additional Encoder subclass, from probabilities into label instead of keeping a list

2020-09-09 16:05 UTC, o8191 commented on variantworks/utils/stitcher.py
> +            current_chunk_seq = decode_consensus(probs[i][second_start_idx:], label_symbols)
It's better to disallow the user to configure the chunk length when stitching

2020-09-10 21:56 UTC, tijyojwad commented on variantworks/utils/stitcher.py
> +    def __init__(self, probs, positions, label_symbols=None):
Ah I just went through the change more closely - @o8191 I was actually thinking we should take the `decode_consensus` function as an argument. We don't know if argmax is the right way to decode it always, so best to leave that to the user.

2020-09-14 09:09 UTC, tijyojwad requested changes

2020-09-14 09:09 UTC, tijyojwad commented on variantworks/utils/stitcher.py
> +        prev_chunk_seq = decode_consensus(probabilities_chunk[first_start_idx:first_end_idx], label_symbols)
Ah I just went through the change more closely - @o8191 I was actually thinking we should take the decode_consensus function as an argument. We don't know if argmax is the right way to decode it always, so best to leave that to the user.

2020-09-14 15:24 UTC, o8191 commented on variantworks/utils/stitcher.py
> +        prev_chunk_seq = decode_consensus(probabilities_chunk[first_start_idx:first_end_idx], label_symbols)
Fixed

2020-09-14 19:00 UTC, tijyojwad approved these changes

2020-09-14 19:00 UTC, merged