[vcfio] update VCF writing code
clara-parabricks/VariantWorks pull request #114
Opened 2020-08-28 18:11 UTC by tijyojwad

Several major changes in this PR - 

1. Move VCFResultWriter to VCFWriter
2. Make VCFWriter interface start from any arbitrary VCF dataframe
3. Generate custom headers based on contents of VCF dataframe
4. Fix bugs in VCF writing code, add multi threaded processing
5. Update tests and samples

Closes #102

2020-09-08 11:05 UTC, o8191 requested changes

2020-09-08 11:05 UTC, o8191 commented on tests/test_vcfio.py
> +    vcf_reader_updated = VCFReader(output_path,
When executing this test through an IDE where stdout/stderr are not captured, we get warnings since the output file not indexed:
```
[W::vcf_parse] Contig '1' is not defined in the header. (Quick workaround: index the file with tabix.)
[W::vcf_parse] Contig '1' is not defined in the header. (Quick workaround: index the file with tabix.)
[W::vcf_parse] Contig '1' is not defined in the header. (Quick workaround: index the file with tabix.)
[W::vcf_parse] Contig '1' is not defined in the header. (Quick workaround: index the file with tabix.)
[W::vcf_parse] Contig '1' is not defined in the header. (Quick workaround: index the file with tabix.)[W::vcf_parse] 
Contig '1' is not defined in the header. (Quick workaround: index the file with tabix.)
[W::vcf_parse] Contig '1' is not defined in the header. (Quick workaround: index the file with tabix.)
[W::vcf_parse] Contig '1' is not defined in the header. (Quick workaround: index the file with tabix.)
[W::vcf_parse] Contig '1' is not defined in the header. (Quick workaround: index the file with tabix.)
[W::vcf_parse] Contig '1' is not defined in the header. (Quick workaround: index the file with tabix.)
[W::vcf_parse] Contig '1' is not defined in the header. (Quick workaround: index the file with tabix.)
[W::vcf_parse] Contig '1' is not defined in the header. (Quick workaround: index the file with tabix.)
```
We can use the fixture again before this line:
```
    # Index output file content with tabix
    with open(output_path, "rb") as in_file:
        data = in_file.read()
    tmp_output_file_path, _ = get_created_vcf_tabix_files(data)

    # Validate output files format and make sure the outputted genotype for each record matches to the network output
    vcf_reader_updated = VCFReader(tmp_output_file_path,
```

2020-09-14 15:05 UTC, edawson approved these changes

2020-09-15 16:57 UTC, tijyojwad commented on variantworks/io/vcfio.py
> +
good catch, done

2020-09-15 16:57 UTC, tijyojwad commented on variantworks/io/vcfio.py
> +        df_list = [item for sublist in df_lists for item in sublist if len(item) > 0]
done

2020-09-15 16:57 UTC, tijyojwad commented on variantworks/io/vcfio.py
> +                regex = re.compile(r"FILTER_(.*)")
great point, added `^`

2020-09-15 16:58 UTC, tijyojwad commented on variantworks/io/vcfio.py
> +                    regex = re.compile(r"{}_(.*)".format(sample))
for generating the header we also need to capture the name of the field after the sample name, and with the regex match we can do both at the same time :). hence regex. and I've added `^` here too!

2020-09-15 16:59 UTC, tijyojwad commented on variantworks/io/vcfio.py
> +        self._standard_headers = set(["chrom",
Since `QUAL` appears as a standard field in VCF, I added it here

2020-09-15 19:32 UTC, edawson commented on variantworks/io/vcfio.py
> +        self._standard_headers = set(["chrom",
I see - we won't need it for merges (or MAF format), but that makes sense.

2020-09-15 19:34 UTC, edawson approved these changes
Regex changes and pool management look good!

2020-09-15 19:36 UTC, edawson requested changes

2020-09-15 19:36 UTC, edawson commented on variantworks/io/vcfio.py
>              Default value.
Could you add a note in the docs that an `np.nan` is returned for float values?

2020-09-15 19:36 UTC, edawson commented on variantworks/io/vcfio.py
> +            return np.iinfo(np.int32).min
Why int_min and not nan here? I like the fixed-width typing though.

2020-09-16 03:53 UTC, tijyojwad commented on variantworks/io/vcfio.py
> +            return np.iinfo(np.int32).min
there's no nan equivalent for integers, and if it force it to be nan then the whole column becomes a float :(

2020-09-16 04:00 UTC, tijyojwad commented on variantworks/io/vcfio.py
>              Default value.
Absolutely - will do

2020-09-16 04:03 UTC, tijyojwad commented on tests/test_vcfio.py
> +    vcf_reader_updated = VCFReader(output_path,
awesome suggestion, implemented. thanks @o8191 !

2020-09-17 14:39 UTC, edawson approved these changes
Looks great! One minor change in docs suggested (namespacing NaN to reflect that it's numpy's definition and not elsewhere's), but otherwise approved!

2020-09-17 14:39 UTC, edawson commented on variantworks/io/vcfio.py
> +        float = NaN
Can we specify "numpy.NaN" and "numpy.int32" here? If I remember right NaN is not consistently defined across packages.

2020-09-17 14:39 UTC, edawson commented on variantworks/io/vcfio.py
> +            return np.iinfo(np.int32).min
Ah - that makes sense!

2020-09-17 15:58 UTC, tijyojwad commented on variantworks/io/vcfio.py
> +        float = NaN
Yep good point - addressed it

2020-09-17 16:10 UTC, o8191 approved these changes

2020-09-17 16:13 UTC, edawson approved these changes

2020-09-17 18:35 UTC, merged