Added rough draft of Parallel Data Loader
clara-parabricks/VariantWorks pull request #115
Opened 2020-09-02 19:34 UTC by rahulmohan

2020-09-03 23:14 UTC, tijyojwad requested changes

2020-09-08 23:09 UTC, tijyojwad commented on samples/simple_consensus_caller/pileup_hdf5_generator.py
> +    features = np.stack(features, axis=0)
Tracking issue in https://github.com/clara-parabricks/VariantWorks/issues/117

2020-09-15 14:02 UTC, tijyojwad commented on samples/simple_consensus_caller/pileup_hdf5_generator.py
> +    encoding_chunks = sliding_window(encoding, window=CHUNK_LEN, step=CHUNK_LEN - CHUNK_OVLP)
update - the iterator is automatically unrolled in the `np.stack` call

2020-09-15 14:05 UTC, tijyojwad requested changes

2020-09-15 14:05 UTC, tijyojwad commented on samples/simple_consensus_caller/pileup_hdf5_generator.py
> +    CHUNK_LEN = args.chunk_len
instead of having these as global, we can pass them into the `encode` function as arguments through the `partial` function setup on line 60

2020-09-16 08:18 UTC, rahulmohan commented
Tested on real data and this code now properly generates a HDF5 file using multiple threads in parallel.

2020-09-16 19:11 UTC, tijyojwad approved these changes

2020-09-16 19:26 UTC, merged