VCFReader re-implemented with pysam
clara-parabricks/VariantWorks pull request #141
Opened 2020-11-04 22:06 UTC by ntadimeti

Using pysam instead of cyvcf2 gives around 27% gain in time.

2020-11-13 21:36 UTC, tijyojwad requested changes
overall looks really good!

2020-11-13 21:36 UTC, tijyojwad commented on variantworks/io/vcfio.py
> -import cyvcf2
can you also remove this from our requirements.txt file?

2020-11-13 21:36 UTC, tijyojwad commented on variantworks/io/vcfio.py
> +        elif isinstance(header_number, numbers.Number):
I've never used the `number` module before - cis this because `pysam` returns a `numbers.Number` object?

2020-11-13 21:36 UTC, tijyojwad commented
@ntadimeti I'm happy with these changes overall, so let's merge them in :).

2020-11-16 19:43 UTC, ntadimeti commented on variantworks/io/vcfio.py
> +        elif isinstance(header_number, numbers.Number):
numbers.Number checks for all types of numbers (int, float etc). Since the header_number can be of different types, figured this would be cleaner.

2020-11-16 20:21 UTC, ntadimeti commented on variantworks/io/vcfio.py
> -import cyvcf2
done

2020-11-17 04:15 UTC, tijyojwad commented on variantworks/io/vcfio.py
> +        elif isinstance(header_number, numbers.Number):
the `header_number` should be either an integer or a character. As per the VCF spec -
```
The Number entry is an Integer that describes the number of values that can be included with the INFO field. For example, if the INFO field contains a single number, then this value should be 1; if the INFO field describes a pair of numbers, then this value should be 2 and so on. There are also certain special characters used to define special cases:
• If the field has one value per alternate allele then this value should be ‘A’.
• If the field has one value for each possible allele (including the reference), then this value should be ‘R’.
• If the field has one value for each possible genotype (more relevant to the FORMAT tags) then this value should be ‘G’.
• If the number of possible values varies, is unknown, or is unbounded, then this value should be ‘.’.
The ‘Flag’ type indicates that the INFO field does not contain a Value entry, and hence the Number should be 0 in this case.
```

2020-11-30 17:01 UTC, tijyojwad approved these changes

2020-11-30 17:02 UTC, tijyojwad commented
@ntadimeti changes look good, approving. feel free to merge once the CI errors are resolved.

2020-11-30 17:48 UTC, merged