Brass BEDPE
clara-parabricks/VariantWorks pull request #153
Opened 2020-11-23 21:36 UTC by mp15

Adds support for BEDPE that use commented headers. Incorporates #152.

2020-11-23 21:36 UTC, GPUtester commented
Can one of the admins verify this patch?

2020-11-23 22:42 UTC, tijyojwad requested changes

2020-11-23 22:42 UTC, tijyojwad commented on variantworks/io/bedio.py
> +    def __init__(self, bed_path, bed_type, header_is_comment=False):
could you add documentation for this new arg to the doc string below?

2020-11-23 22:42 UTC, tijyojwad commented on variantworks/io/bedio.py
> +            self._df = self._read_data(self._bed_path)
This is a pretty nice change. I'm thinking of making this a standard pre-processing for all BED files, so we don't have to maintain a separate path in the code. Does this work for the typical BED files without a header section? If so, then I would just remove the `header_is_comment` conditional and call the `_read_data` function directly on all inputs. The `uniquify` function might do some extra work, but it'll be quite minimal.

2020-11-23 22:42 UTC, tijyojwad commented on variantworks/io/bedio.py
> +            self._df = self._read_data(self._bed_path)
and we could add to the docs how non-unique header names are handled, i.e. with a counter suffix by default

2020-11-24 14:56 UTC, mp15 commented on variantworks/io/bedio.py
> +    def __init__(self, bed_path, bed_type, header_is_comment=False):
Done

2020-11-24 14:58 UTC, mp15 commented on variantworks/io/bedio.py
> +            self._df = self._read_data(self._bed_path)
Alas the BEDPE implementations are a bit fast and loose when it comes to whether or not the header is a comment or not which is why I created a second code path.

2020-11-24 20:15 UTC, tijyojwad commented on variantworks/io/bedio.py
> +            self._df = self._read_data(self._bed_path)
Oh that's a bummer. In that case the change looks good to me! I'll add a test case for this code path using the file you linked [here](https://github.com/clara-parabricks/VariantWorks/issues/144#issuecomment-733039660) once this PR goes in

2020-11-24 20:16 UTC, tijyojwad approved these changes

2020-11-24 20:16 UTC, merged