Modified cnn
clara-parabricks/VariantWorks pull request #165
Opened 2021-03-29 03:50 UTC by avantikalal

Modified CNN model to include two conv layers with padding, and variable kernel size. Added more user options including learning rate.

2021-04-03 00:44 UTC, ohadmo requested changes
Looks good to me.
Can you update the `samples/simple_consensus_caller/README.md` since we renamed several files?

2021-04-03 00:44 UTC, ohadmo commented on variantworks/networks.py
> +        self.classifier = nn.Linear(2*gru_size, self.num_output_logits)
Shouldn't the `in_features` for the `nn.Linear` be equal to `gru_size` and not `2*gru_size`?

2021-04-03 17:58 UTC, avantikalal commented on variantworks/networks.py
> +        self.classifier = nn.Linear(2*gru_size, self.num_output_logits)
It's `2*gru_size` since the GRU layer is bidirectional.

2021-04-05 15:38 UTC, ohadmo approved these changes

2021-04-05 16:06 UTC, merged